### Create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "john doe",
  "email": "",
  "address": "123 main street",
  "dateOfBirth": "2003-05-17",
  "registeredDate": "2003-05-17"
}

###